package ir.zeusdns.zeusdnschanger.utils

import ir.zeusdns.zeusdnschanger.viewmodel.MainViewModel
import java.util.Locale

object Localization {
    private val englishStrings = mapOf(
        "home" to "Home",
        "dns" to "Dns",
        "pro" to "Pro",
        "about" to "About",
        "connected" to "CONNECTED",
        "disconnected" to "DISCONNECTED",
        "upload" to "Upload",
        "download" to "Download",
        "address" to "Address",
        "tap_to_get_ip" to "Tap to get IP",
        "getting_ip" to "Getting ip...",
        "pro_registration" to "Pro Registration",
        "enter_your_token" to "Enter your token",
        "your_token" to "Your Token...",
        "your_ip" to "Your IP:",
        "getting_ip_ellipsis" to "Getting IP...",
        "request_successful" to "Request Successful",
        "request_failed" to "Request Failed",
        "sending" to "Sending...",
        "send_token" to "Send Token",
        "please_enter_a_token" to "Please enter a token",
        "dns_section" to "DNS Section",
        "this_section_is_under_development" to "This section is under development",
        "about_zeusdns" to "About ZeusDNS",
        "dns_free" to "Free DNS",
        "dns_pro" to "Pro DNS",
        "add_custom_dns" to "Add Custom DNS",
        "add_dns_server" to "Add DNS Server",
        "enter_dns_name" to "Enter DNS name",
        "enter_primary_dns" to "Enter primary DNS",
        "enter_secondary_dns" to "Enter secondary DNS (optional)",
        "primary_dns" to "Primary DNS",
        "secondary_dns" to "Secondary DNS",
        "primary_main" to "Primary: ",
        "secondary_main" to "Secondary: ",
        "example_dns_name" to "Example: My DNS",
        "example_primary_dns" to "Example: 8.8.8.8",
        "example_secondary_dns" to "Example: 8.8.4.4",
        "cancel" to "Cancel",
        "add" to "Add",
        "active" to "Active",
        "set_as_active" to "Set as Active",
        "delete" to "Delete",
        "copied" to "Copied",
        "copy_address" to "Copy Address",
        "dns_server_added" to "DNS server added",
        "invalid_dns_address" to "Invalid DNS address format",
        "fill_required_fields" to "Please fill Name and Primary DNS",
        "server_already_exists" to "Server already exists",
        "tap_to_copy" to "Tap to copy",
        "both_dns_active" to "Both DNS servers active",
        "free_dns_servers" to "Free DNS Servers",
        "pro_dns_servers" to "Pro DNS Servers",
        "custom_dns_servers" to "Custom DNS Servers",
        "settings" to "Settings",
        "appearance" to "Appearance",
        "notifications" to "Notifications",
        "connection" to "Connection",
        "dark_mode" to "Dark Mode",
        "use_dark_theme" to "Use dark theme",
        "follow_system" to "Follow System",
        "use_system_theme_settings" to "Use system theme settings",
        "show_notifications" to "Enable speed display",
        "show_connection_notifications" to "Display current speed in notifications",
        "auto_connect" to "Auto Connect",
        "auto_connect_on_app_start" to "Auto connect on app start",
        "default_dns_selection" to "Default DNS Selection",
        "active_dns_on_startup" to "Active DNS on startup",
        "app_version" to "App Version",
        "current_version" to "Current Version:",
        "about_page" to "About Page",
        "more_info_about_zeusdns" to "More info about ZeusDNS",
        "contact_support" to "Contact Support",
        "report_issue_or_suggestion" to "Report issue or suggestion",
        "terms_and_conditions" to "Terms and Conditions",
        "service_usage_rules" to "Service usage rules",
        "privacy_policy" to "Privacy Policy",
        "how_we_manage_your_data" to "How we manage your data",
        "all_rights_reserved" to "All rights reserved",
        "select_theme" to "Select Theme",
        "dark" to "Dark",
        "light" to "Light",
        "system" to "System",
        "confirm" to "Confirm",
        "theme_applied" to "Theme applied",
        "language" to "Language",
        "select_language" to "Select Language",
        "english" to "English",
        "persian" to "Persian",
        "clear_cache" to "Clear Cache",
        "clear_app_cache" to "Clear app cache",
        "cache_cleared" to "Cache cleared successfully",
        "reset_settings" to "Reset Settings",
        "reset_all_settings_to_default" to "Reset all settings to default",
        "settings_reset" to "Settings reset to default",
        "maintenance" to "Maintenance",
        "telegram_support" to "Telegram Support",
        "telegram_channel" to "Telegram Channel",
        "website" to "Website",
        "clear_cache_confirmation" to "Are you sure you want to clear app cache?",
        "reset_settings_confirmation" to "Are you sure you want to reset all settings to default?",
        "language_restart_message" to "Please restart app to apply language changes",
        "cache_size" to "Cache size:",
        "open_link" to "Open link",
        "active_dns" to "Active DNS",
        "active_dns_subtitle" to "Currently selected DNS server",
        "ip_copied" to "IP address copied",
        "dns_name_required" to "DNS name is required",
        "primary_dns_required" to "Primary DNS is required",
        "primary_dns_invalid" to "Invalid DNS address format",
        "secondary_dns_invalid" to "Invalid secondary DNS format",
        "ping_test" to "Ping Test",
        "ping_primary" to "Ping Primary",
        "ping_secondary" to "Ping Secondary",
        "ping_all" to "Ping All",
        "pinging" to "Pinging...",
        "latency" to "Latency:",
        "ping_failed" to "Ping Failed",
        "ping_success" to "Ping Success",
        "ping_idle" to "Click to test ping",
        "auto_ping_on_start" to "Auto ping on start",
        "auto_update_title" to "Auto Update IP",
        "auto_update_desc" to "Check & update in background",
        "stop_auto_update" to "Stop Auto Update",
        "monitoring_ip" to "Monitoring IP changes...",
        "service_started" to "Monitoring IP service started",
        "service_stopped" to "Monitoring IP service stopped",
        "update_interval" to "Update Interval"
    )

    private val persianStrings = mapOf(
        "home" to "خانه",
        "dns" to "دی‌ان‌اس",
        "pro" to "حرفه‌ای",
        "about" to "درباره",
        "connected" to "متصل",
        "disconnected" to "قطع",
        "upload" to "آپلود",
        "download" to "دانلود",
        "address" to "آدرس",
        "tap_to_get_ip" to "برای دریافت آی‌پی ضربه بزنید",
        "getting_ip" to "دریافت آی‌پی...",
        "pro_registration" to "ثبت‌نام حرفه‌ای",
        "enter_your_token" to "توکن خود را وارد کنید",
        "your_token" to "توکن شما...",
        "your_ip" to "آی‌پی شما:",
        "getting_ip_ellipsis" to "دریافت آی‌پی...",
        "request_successful" to "درخواست موفق",
        "request_failed" to "درخواست ناموفق",
        "sending" to "در حال ارسال...",
        "send_token" to "ارسال توکن",
        "please_enter_a_token" to "لطفاً یک توکن وارد کنید",
        "dns_section" to "بخش دی‌ان‌اس",
        "this_section_is_under_development" to "این بخش در حال توسعه است",
        "about_zeusdns" to "درباره ZeusDNS",
        "dns_free" to "دی‌ان‌اس رایگان",
        "dns_pro" to "دی‌ان‌اس حرفه‌ای",
        "add_custom_dns" to "افزودن دی‌ان‌اس سفارشی",
        "add_dns_server" to "افزودن سرور دی‌ان‌اس",
        "enter_dns_name" to "نام دی‌ان‌اس را وارد کنید",
        "enter_primary_dns" to "دی‌ان‌اس اصلی را وارد کنید",
        "enter_secondary_dns" to "دی‌ان‌اس ثانویه را وارد کنید (اختیاری)",
        "primary_dns" to "دی‌ان‌اس اصلی",
        "secondary_dns" to "دی‌ان‌اس ثانویه",
        "primary_main" to "اصلی: ",
        "secondary_main" to "ثانویه: ",
        "example_dns_name" to "مثال: دی‌ان‌اس من",
        "example_primary_dns" to "مثال: 8.8.8.8",
        "example_secondary_dns" to "مثال: 8.8.4.4",
        "cancel" to "لغو",
        "add" to "افزودن",
        "active" to "فعال",
        "set_as_active" to "تنظیم به عنوان فعال",
        "delete" to "حذف",
        "copied" to "کپی شد",
        "copy_address" to "کپی آدرس",
        "dns_server_added" to "سرور دی‌ان‌اس اضافه شد",
        "invalid_dns_address" to "فرمت آدرس دی‌ان‌اس نامعتبر است",
        "fill_required_fields" to "لطفا نام و دی‌ان‌اس اصلی را وارد کنید",
        "server_already_exists" to "سرور از قبل وجود دارد",
        "tap_to_copy" to "برای کپی ضربه بزنید",
        "both_dns_active" to "هر دو سرور دی‌ان‌اس فعال هستند",
        "free_dns_servers" to "سرورهای دی‌ان‌اس رایگان",
        "pro_dns_servers" to "سرورهای دی‌ان‌اس حرفه‌ای",
        "custom_dns_servers" to "سرورهای دی‌ان‌اس سفارشی",
        "settings" to "تنظیمات",
        "appearance" to "ظاهر و نمایش",
        "notifications" to "اعلان‌ها",
        "connection" to "اتصال",
        "dark_mode" to "حالت تاریک",
        "use_dark_theme" to "استفاده از تم تاریک",
        "follow_system" to "پیروی از سیستم",
        "use_system_theme_settings" to "استفاده از تنظیمات تم سیستم",
        "show_notifications" to "فعال سازی نمایش سرعت",
        "show_connection_notifications" to "نمایش سرعت فعلی در اعلان\u200Cها",
        "auto_connect" to "اتصال خودکار",
        "auto_connect_on_app_start" to "اتصال خودکار هنگام باز کردن برنامه",
        "default_dns_selection" to "انتخاب دی‌ان‌اس پیشفرض",
        "active_dns_on_startup" to "دی‌ان‌اس فعال هنگام شروع",
        "app_version" to "ورژن برنامه",
        "current_version" to "نسخه فعلی:",
        "about_page" to "صفحه درباره",
        "more_info_about_zeusdns" to "اطلاعات بیشتر درباره ZeusDNS",
        "contact_support" to "ارتباط با پشتیبانی",
        "report_issue_or_suggestion" to "گزارش مشکل یا پیشنهاد",
        "terms_and_conditions" to "شرایط و ضوابط",
        "service_usage_rules" to "قوانین استفاده از سرویس",
        "privacy_policy" to "سیاست حریم خصوصی",
        "how_we_manage_your_data" to "نحوه مدیریت داده‌های شما",
        "all_rights_reserved" to "تمام حقوق محفوظ است",
        "select_theme" to "انتخاب تم",
        "dark" to "تاریک",
        "light" to "روشن",
        "system" to "سیستمی",
        "confirm" to "تایید",
        "theme_applied" to "تم اعمال شد",
        "language" to "زبان",
        "select_language" to "انتخاب زبان",
        "english" to "انگلیسی",
        "persian" to "فارسی",
        "clear_cache" to "پاک کردن کش",
        "clear_app_cache" to "پاک کردن کش برنامه",
        "cache_cleared" to "کش با موفقیت پاک شد",
        "reset_settings" to "بازنشانی تنظیمات",
        "reset_all_settings_to_default" to "بازنشانی تمام تنظیمات به پیش‌فرض",
        "settings_reset" to "تنظیمات به حالت پیش‌فرض بازنشانی شد",
        "maintenance" to "نگهداری",
        "telegram_support" to "پشتیبانی تلگرام",
        "telegram_channel" to "کانال تلگرام",
        "website" to "وبسایت",
        "clear_cache_confirmation" to "آیا مطمئن هستید که می‌خواهید کش برنامه را پاک کنید؟",
        "reset_settings_confirmation" to "آیا مطمئن هستید که می‌خواهید تمام تنظیمات را به حالت پیش‌فرض بازنشانی کنید؟",
        "language_restart_message" to "برای اعمال تغییر زبان، برنامه را مجدداً باز کنید",
        "cache_size" to "حجم کش:",
        "open_link" to "باز کردن لینک",
        "active_dns" to "دی‌ان‌اس فعال",
        "active_dns_subtitle" to "سرور دی‌ان‌اس انتخاب شده فعلی",
        "ip_copied" to "آدرس آی‌پی کپی شد",
        "dns_name_required" to "نام دی‌ان‌اس الزامی است",
        "primary_dns_required" to "دی‌ان‌اس اصلی الزامی است",
        "primary_dns_invalid" to "فرمت آدرس دی‌ان‌اس نامعتبر است",
        "secondary_dns_invalid" to "فرمت دی‌ان‌اس ثانویه نامعتبر است",
        "ping_test" to "تست پینگ",
        "ping_primary" to "پینگ اصلی",
        "ping_secondary" to "پینگ ثانویه",
        "ping_all" to "پینگ همه",
        "pinging" to "در حال پینگ...",
        "latency" to "تاخیر:",
        "ping_failed" to "پینگ ناموفق",
        "ping_success" to "پینگ موفق",
        "ping_idle" to "برای تست پینگ کلیک کنید",
        "auto_ping_on_start" to "پینگ خودکار هنگام شروع",
        "auto_update_title" to "بروزرسانی خودکار آی‌پی",
        "auto_update_desc" to "بررسی و تغییر در پس‌زمینه",
        "stop_auto_update" to "توقف بروزرسانی خودکار",
        "monitoring_ip" to "در حال پایش تغییرات آی‌پی...",
        "service_started" to "سرویس پایش آی‌پی فعال شد",
        "service_stopped" to "سرویس پایش آی‌پی متوقف شد",
        "update_interval" to "بازه زمانی آپدیت"
    )

    fun getString(key: String, viewModel: MainViewModel): String {
        return when (val language = viewModel.appSettings.language) {
            "fa" -> persianStrings[key] ?: englishStrings[key] ?: key
            "en" -> englishStrings[key] ?: key
            else -> {
                val locale = Locale.getDefault()
                if (locale.language == "fa") {
                    persianStrings[key] ?: englishStrings[key] ?: key
                } else {
                    englishStrings[key] ?: key
                }
            }
        }
    }
}